### PR TITLE
Tiered mining size upgrades (including a 5x5)

### PR DESCRIPTION
**Pull request by Anoyomouse**
This PR is based off the previous work for the 5x5 upgrade, but makes it a proper tiered upgrade and allows you to have as many tiers of upgrade by only adding in the upgrade item (no further code changes)

Furthermore, it only allows one size upgrade in the gadget at a time

Unfortunately, because it renames things, if you had a 3x3 upgrade it'll poof away with these changes

### CODE REVIEW

**Comment by Direwolf20-MC** [comment]
Cool thank you for this ;)! I’ll look it over with Mikey. 

Does it mine down 1 up 3 or down 2 up 2? Down 1 up 3 is preferred :)

**Comment by Anoyomouse** [comment]
> Cool thank you for this ;)! I’ll look it over with Mikey.
Woooo!

> Does it mine down 1 up 3 or down 2 up 2? Down 1 up 3 is preferred :)
So, currently it does the 1 down 3 up when looking at a wall and you're looking at least 2 blocks down or up, otherwise it does the pure 5x5

I'm actually in the process of adding in a "size mode" option that lets you toggle pathways (1 down, x - 2 up)

**Comment by Anoyomouse** [comment]
Might have gone a bit overboard, you now have a choice to automatically do 2 down n up, or to do normal mining

I also decided to add (mostly for testing, but it's also fun) a 7x7 upgrade, since that really shows off the automatic mode and how it's a little disorienting sometimes

Let me know if there's anything i need to change, or re-think :)

**Comment by Direwolf20-MC** [comment]
Cool thanks, I'll try it out! :)

**Comment by Direwolf20-MC** [comment]
Why do all the JSON files have changes along the lines of sends_telemetry_event and show_notification?

**Comment by Anoyomouse** [comment]
> Why do all the JSON files have changes along the lines of sends_telemetry_event and show_notification?

I did a "runData" on the source, which generated the jsons again, and this appears to be a new tag added by the 1.20.1 NeoForge .. if you look at the main repo, you'll see the cache is only 1.19 (the datagen wasn't run for 1.20)

**Comment by MichaelHillcox** [comment]
Looks good, just one thing:

**Missing lang key**

**Comment by Anoyomouse** [comment]
> Looks good, just one thing:
> 
> **Missing lang key** 

Whoops, totally missed that, i've added it in and re-run the data generator

**Pull request merged**
